### case: limit page sort
GET /series-suggestions?limit=3&page=1&sortBy=name
Content-Type: application/json


# ### case: search
GET /series-suggestions?limit=3&page=1&sortBy=name&search=2
Content-Type: application/json


# ### case: get
GET /series-suggestions/21
Content-Type: application/json